// MainWindow.Designer.cs
// This file is auto-generated by the Windows Forms Designer.
// Do not modify this file manually.

namespace MyLibraryApp
{
    partial class MainWindow
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.tabControlMain = new System.Windows.Forms.TabControl();
            this.tabPageBooks = new System.Windows.Forms.TabPage();
            this.dgvBooks = new System.Windows.Forms.DataGridView();
            this.panelBookButtons = new System.Windows.Forms.Panel();
            this.btnDeleteBook = new System.Windows.Forms.Button();
            this.btnEditBook = new System.Windows.Forms.Button();
            this.btnAddBook = new System.Windows.Forms.Button();
            this.panelBookSearch = new System.Windows.Forms.Panel();
            this.btnClearBookSearch = new System.Windows.Forms.Button();
            this.btnSearchBook = new System.Windows.Forms.Button();
            this.txtSearchBook = new System.Windows.Forms.TextBox();
            this.lblSearchBook = new System.Windows.Forms.Label();
            this.tabPageBorrowers = new System.Windows.Forms.TabPage();
            this.dgvBorrowers = new System.Windows.Forms.DataGridView();
            this.panelBorrowerButtons = new System.Windows.Forms.Panel();
            this.btnDeleteBorrower = new System.Windows.Forms.Button();
            this.btnEditBorrower = new System.Windows.Forms.Button();
            this.btnAddBorrower = new System.Windows.Forms.Button();
            this.panelBorrowerSearch = new System.Windows.Forms.Panel();
            this.btnClearBorrowerSearch = new System.Windows.Forms.Button();
            this.btnSearchBorrower = new System.Windows.Forms.Button();
            this.txtSearchBorrower = new System.Windows.Forms.TextBox();
            this.lblSearchBorrower = new System.Windows.Forms.Label();
            this.tabPageBorrowings = new System.Windows.Forms.TabPage();
            this.dgvBorrowings = new System.Windows.Forms.DataGridView();
            this.panelBorrowingButtons = new System.Windows.Forms.Panel();
            this.btnReturnBook = new System.Windows.Forms.Button();
            this.btnBorrowBook = new System.Windows.Forms.Button();
            this.panelBorrowingSearch = new System.Windows.Forms.Panel();
            this.btnClearBorrowingSearch = new System.Windows.Forms.Button();
            this.btnSearchBorrowing = new System.Windows.Forms.Button();
            this.txtSearchBorrowing = new System.Windows.Forms.TextBox();
            this.lblSearchBorrowing = new System.Windows.Forms.Label();
            this.tabControlMain.SuspendLayout();
            this.tabPageBooks.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.dgvBooks)).BeginInit();
            this.panelBookButtons.SuspendLayout();
            this.panelBookSearch.SuspendLayout();
            this.tabPageBorrowers.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.dgvBorrowers)).BeginInit();
            this.panelBorrowerButtons.SuspendLayout();
            this.panelBorrowerSearch.SuspendLayout();
            this.tabPageBorrowings.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.dgvBorrowings)).BeginInit();
            this.panelBorrowingButtons.SuspendLayout();
            this.panelBorrowingSearch.SuspendLayout();
            this.SuspendLayout();
            // 
            // tabControlMain
            // 
            this.tabControlMain.Controls.Add(this.tabPageBooks);
            this.tabControlMain.Controls.Add(this.tabPageBorrowers);
            this.tabControlMain.Controls.Add(this.tabPageBorrowings);
            this.tabControlMain.Dock = System.Windows.Forms.DockStyle.Fill;
            this.tabControlMain.Font = new System.Drawing.Font("Segoe UI", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.tabControlMain.Location = new System.Drawing.Point(0, 0);
            this.tabControlMain.Name = "tabControlMain";
            this.tabControlMain.SelectedIndex = 0;
            this.tabControlMain.Size = new System.Drawing.Size(984, 561);
            this.tabControlMain.TabIndex = 0;
            // 
            // tabPageBooks
            // 
            this.tabPageBooks.Controls.Add(this.dgvBooks);
            this.tabPageBooks.Controls.Add(this.panelBookButtons);
            this.tabPageBooks.Controls.Add(this.panelBookSearch);
            this.tabPageBooks.Location = new System.Drawing.Point(4, 37);
            this.tabPageBooks.Name = "tabPageBooks";
            this.tabPageBooks.Padding = new System.Windows.Forms.Padding(3);
            this.tabPageBooks.Size = new System.Drawing.Size(976, 520);
            this.tabPageBooks.TabIndex = 0;
            this.tabPageBooks.Text = "Books Management";
            this.tabPageBooks.UseVisualStyleBackColor = true;
            // 
            // dgvBooks
            // 
            this.dgvBooks.AllowUserToAddRows = false;
            this.dgvBooks.AllowUserToDeleteRows = false;
            this.dgvBooks.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            this.dgvBooks.ColumnHeadersHeightSizeMode = System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.AutoSize;
            this.dgvBooks.Dock = System.Windows.Forms.DockStyle.Fill;
            this.dgvBooks.Location = new System.Drawing.Point(3, 53);
            this.dgvBooks.MultiSelect = false;
            this.dgvBooks.Name = "dgvBooks";
            this.dgvBooks.ReadOnly = true;
            this.dgvBooks.RowHeadersWidth = 62;
            this.dgvBooks.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this.dgvBooks.Size = new System.Drawing.Size(970, 414);
            this.dgvBooks.TabIndex = 1;
            // 
            // panelBookButtons
            // 
            this.panelBookButtons.Controls.Add(this.btnDeleteBook);
            this.panelBookButtons.Controls.Add(this.btnEditBook);
            this.panelBookButtons.Controls.Add(this.btnAddBook);
            this.panelBookButtons.Dock = System.Windows.Forms.DockStyle.Bottom;
            this.panelBookButtons.Location = new System.Drawing.Point(3, 467);
            this.panelBookButtons.Name = "panelBookButtons";
            this.panelBookButtons.Size = new System.Drawing.Size(970, 50);
            this.panelBookButtons.TabIndex = 0;
            // 
            // btnDeleteBook
            // 
            this.btnDeleteBook.Font = new System.Drawing.Font("Segoe UI", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnDeleteBook.Location = new System.Drawing.Point(200, 10);
            this.btnDeleteBook.Name = "btnDeleteBook";
            this.btnDeleteBook.Size = new System.Drawing.Size(80, 30);
            this.btnDeleteBook.TabIndex = 2;
            this.btnDeleteBook.Text = "Delete";
            this.btnDeleteBook.UseVisualStyleBackColor = true;
            // 
            // btnEditBook
            // 
            this.btnEditBook.Font = new System.Drawing.Font("Segoe UI", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnEditBook.Location = new System.Drawing.Point(100, 10);
            this.btnEditBook.Name = "btnEditBook";
            this.btnEditBook.Size = new System.Drawing.Size(80, 30);
            this.btnEditBook.TabIndex = 1;
            this.btnEditBook.Text = "Edit";
            this.btnEditBook.UseVisualStyleBackColor = true;
            // 
            // btnAddBook
            // 
            this.btnAddBook.Font = new System.Drawing.Font("Segoe UI", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnAddBook.Location = new System.Drawing.Point(0, 10);
            this.btnAddBook.Name = "btnAddBook";
            this.btnAddBook.Size = new System.Drawing.Size(80, 30);
            this.btnAddBook.TabIndex = 0;
            this.btnAddBook.Text = "Add";
            this.btnAddBook.UseVisualStyleBackColor = true;
            this.btnAddBook.Click += new System.EventHandler(this.btnAddBook_Click_1);
            // 
            // panelBookSearch
            // 
            this.panelBookSearch.Controls.Add(this.btnClearBookSearch);
            this.panelBookSearch.Controls.Add(this.btnSearchBook);
            this.panelBookSearch.Controls.Add(this.txtSearchBook);
            this.panelBookSearch.Controls.Add(this.lblSearchBook);
            this.panelBookSearch.Dock = System.Windows.Forms.DockStyle.Top;
            this.panelBookSearch.Location = new System.Drawing.Point(3, 3);
            this.panelBookSearch.Name = "panelBookSearch";
            this.panelBookSearch.Size = new System.Drawing.Size(970, 50);
            this.panelBookSearch.TabIndex = 2;
            // 
            // btnClearBookSearch
            // 
            this.btnClearBookSearch.Font = new System.Drawing.Font("Segoe UI", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnClearBookSearch.Location = new System.Drawing.Point(500, 10);
            this.btnClearBookSearch.Name = "btnClearBookSearch";
            this.btnClearBookSearch.Size = new System.Drawing.Size(80, 30);
            this.btnClearBookSearch.TabIndex = 3;
            this.btnClearBookSearch.Text = "Clear";
            this.btnClearBookSearch.UseVisualStyleBackColor = true;
            // 
            // btnSearchBook
            // 
            this.btnSearchBook.Font = new System.Drawing.Font("Segoe UI", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnSearchBook.Location = new System.Drawing.Point(410, 10);
            this.btnSearchBook.Name = "btnSearchBook";
            this.btnSearchBook.Size = new System.Drawing.Size(80, 30);
            this.btnSearchBook.TabIndex = 2;
            this.btnSearchBook.Text = "Search";
            this.btnSearchBook.UseVisualStyleBackColor = true;
            // 
            // txtSearchBook
            // 
            this.txtSearchBook.Font = new System.Drawing.Font("Segoe UI", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtSearchBook.Location = new System.Drawing.Point(100, 13);
            this.txtSearchBook.Name = "txtSearchBook";
            this.txtSearchBook.Size = new System.Drawing.Size(300, 33);
            this.txtSearchBook.TabIndex = 1;
            // 
            // lblSearchBook
            // 
            this.lblSearchBook.AutoSize = true;
            this.lblSearchBook.Font = new System.Drawing.Font("Segoe UI", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblSearchBook.Location = new System.Drawing.Point(10, 16);
            this.lblSearchBook.Name = "lblSearchBook";
            this.lblSearchBook.Size = new System.Drawing.Size(124, 28);
            this.lblSearchBook.TabIndex = 0;
            this.lblSearchBook.Text = "Search Book:";
            // 
            // tabPageBorrowers
            // 
            this.tabPageBorrowers.Controls.Add(this.dgvBorrowers);
            this.tabPageBorrowers.Controls.Add(this.panelBorrowerButtons);
            this.tabPageBorrowers.Controls.Add(this.panelBorrowerSearch);
            this.tabPageBorrowers.Location = new System.Drawing.Point(4, 37);
            this.tabPageBorrowers.Name = "tabPageBorrowers";
            this.tabPageBorrowers.Padding = new System.Windows.Forms.Padding(3);
            this.tabPageBorrowers.Size = new System.Drawing.Size(976, 520);
            this.tabPageBorrowers.TabIndex = 1;
            this.tabPageBorrowers.Text = "Borrowers Management";
            this.tabPageBorrowers.UseVisualStyleBackColor = true;
            // 
            // dgvBorrowers
            // 
            this.dgvBorrowers.AllowUserToAddRows = false;
            this.dgvBorrowers.AllowUserToDeleteRows = false;
            this.dgvBorrowers.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            this.dgvBorrowers.ColumnHeadersHeightSizeMode = System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.AutoSize;
            this.dgvBorrowers.Dock = System.Windows.Forms.DockStyle.Fill;
            this.dgvBorrowers.Location = new System.Drawing.Point(3, 53);
            this.dgvBorrowers.MultiSelect = false;
            this.dgvBorrowers.Name = "dgvBorrowers";
            this.dgvBorrowers.ReadOnly = true;
            this.dgvBorrowers.RowHeadersWidth = 62;
            this.dgvBorrowers.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this.dgvBorrowers.Size = new System.Drawing.Size(970, 414);
            this.dgvBorrowers.TabIndex = 1;
            // 
            // panelBorrowerButtons
            // 
            this.panelBorrowerButtons.Controls.Add(this.btnDeleteBorrower);
            this.panelBorrowerButtons.Controls.Add(this.btnEditBorrower);
            this.panelBorrowerButtons.Controls.Add(this.btnAddBorrower);
            this.panelBorrowerButtons.Dock = System.Windows.Forms.DockStyle.Bottom;
            this.panelBorrowerButtons.Location = new System.Drawing.Point(3, 467);
            this.panelBorrowerButtons.Name = "panelBorrowerButtons";
            this.panelBorrowerButtons.Size = new System.Drawing.Size(970, 50);
            this.panelBorrowerButtons.TabIndex = 0;
            // 
            // btnDeleteBorrower
            // 
            this.btnDeleteBorrower.Font = new System.Drawing.Font("Segoe UI", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnDeleteBorrower.Location = new System.Drawing.Point(200, 10);
            this.btnDeleteBorrower.Name = "btnDeleteBorrower";
            this.btnDeleteBorrower.Size = new System.Drawing.Size(80, 30);
            this.btnDeleteBorrower.TabIndex = 2;
            this.btnDeleteBorrower.Text = "Delete";
            this.btnDeleteBorrower.UseVisualStyleBackColor = true;
            // 
            // btnEditBorrower
            // 
            this.btnEditBorrower.Font = new System.Drawing.Font("Segoe UI", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnEditBorrower.Location = new System.Drawing.Point(100, 10);
            this.btnEditBorrower.Name = "btnEditBorrower";
            this.btnEditBorrower.Size = new System.Drawing.Size(80, 30);
            this.btnEditBorrower.TabIndex = 1;
            this.btnEditBorrower.Text = "Edit";
            this.btnEditBorrower.UseVisualStyleBackColor = true;
            // 
            // btnAddBorrower
            // 
            this.btnAddBorrower.Font = new System.Drawing.Font("Segoe UI", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnAddBorrower.Location = new System.Drawing.Point(0, 10);
            this.btnAddBorrower.Name = "btnAddBorrower";
            this.btnAddBorrower.Size = new System.Drawing.Size(80, 30);
            this.btnAddBorrower.TabIndex = 0;
            this.btnAddBorrower.Text = "Add";
            this.btnAddBorrower.UseVisualStyleBackColor = true;
            // 
            // panelBorrowerSearch
            // 
            this.panelBorrowerSearch.Controls.Add(this.btnClearBorrowerSearch);
            this.panelBorrowerSearch.Controls.Add(this.btnSearchBorrower);
            this.panelBorrowerSearch.Controls.Add(this.txtSearchBorrower);
            this.panelBorrowerSearch.Controls.Add(this.lblSearchBorrower);
            this.panelBorrowerSearch.Dock = System.Windows.Forms.DockStyle.Top;
            this.panelBorrowerSearch.Location = new System.Drawing.Point(3, 3);
            this.panelBorrowerSearch.Name = "panelBorrowerSearch";
            this.panelBorrowerSearch.Size = new System.Drawing.Size(970, 50);
            this.panelBorrowerSearch.TabIndex = 2;
            // 
            // btnClearBorrowerSearch
            // 
            this.btnClearBorrowerSearch.Font = new System.Drawing.Font("Segoe UI", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnClearBorrowerSearch.Location = new System.Drawing.Point(520, 10);
            this.btnClearBorrowerSearch.Name = "btnClearBorrowerSearch";
            this.btnClearBorrowerSearch.Size = new System.Drawing.Size(80, 30);
            this.btnClearBorrowerSearch.TabIndex = 3;
            this.btnClearBorrowerSearch.Text = "Clear";
            this.btnClearBorrowerSearch.UseVisualStyleBackColor = true;
            // 
            // btnSearchBorrower
            // 
            this.btnSearchBorrower.Font = new System.Drawing.Font("Segoe UI", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnSearchBorrower.Location = new System.Drawing.Point(430, 10);
            this.btnSearchBorrower.Name = "btnSearchBorrower";
            this.btnSearchBorrower.Size = new System.Drawing.Size(80, 30);
            this.btnSearchBorrower.TabIndex = 2;
            this.btnSearchBorrower.Text = "Search";
            this.btnSearchBorrower.UseVisualStyleBackColor = true;
            // 
            // txtSearchBorrower
            // 
            this.txtSearchBorrower.Font = new System.Drawing.Font("Segoe UI", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtSearchBorrower.Location = new System.Drawing.Point(120, 13);
            this.txtSearchBorrower.Name = "txtSearchBorrower";
            this.txtSearchBorrower.Size = new System.Drawing.Size(300, 33);
            this.txtSearchBorrower.TabIndex = 1;
            // 
            // lblSearchBorrower
            // 
            this.lblSearchBorrower.AutoSize = true;
            this.lblSearchBorrower.Font = new System.Drawing.Font("Segoe UI", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblSearchBorrower.Location = new System.Drawing.Point(10, 16);
            this.lblSearchBorrower.Name = "lblSearchBorrower";
            this.lblSearchBorrower.Size = new System.Drawing.Size(159, 28);
            this.lblSearchBorrower.TabIndex = 0;
            this.lblSearchBorrower.Text = "Search Borrower:";
            // 
            // tabPageBorrowings
            // 
            this.tabPageBorrowings.Controls.Add(this.dgvBorrowings);
            this.tabPageBorrowings.Controls.Add(this.panelBorrowingButtons);
            this.tabPageBorrowings.Controls.Add(this.panelBorrowingSearch);
            this.tabPageBorrowings.Location = new System.Drawing.Point(4, 37);
            this.tabPageBorrowings.Name = "tabPageBorrowings";
            this.tabPageBorrowings.Padding = new System.Windows.Forms.Padding(3);
            this.tabPageBorrowings.Size = new System.Drawing.Size(976, 520);
            this.tabPageBorrowings.TabIndex = 2;
            this.tabPageBorrowings.Text = "Borrowings";
            this.tabPageBorrowings.UseVisualStyleBackColor = true;
            // 
            // dgvBorrowings
            // 
            this.dgvBorrowings.AllowUserToAddRows = false;
            this.dgvBorrowings.AllowUserToDeleteRows = false;
            this.dgvBorrowings.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            this.dgvBorrowings.ColumnHeadersHeightSizeMode = System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.AutoSize;
            this.dgvBorrowings.Dock = System.Windows.Forms.DockStyle.Fill;
            this.dgvBorrowings.Location = new System.Drawing.Point(3, 53);
            this.dgvBorrowings.MultiSelect = false;
            this.dgvBorrowings.Name = "dgvBorrowings";
            this.dgvBorrowings.ReadOnly = true;
            this.dgvBorrowings.RowHeadersWidth = 62;
            this.dgvBorrowings.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this.dgvBorrowings.Size = new System.Drawing.Size(970, 414);
            this.dgvBorrowings.TabIndex = 1;
            // 
            // panelBorrowingButtons
            // 
            this.panelBorrowingButtons.Controls.Add(this.btnReturnBook);
            this.panelBorrowingButtons.Controls.Add(this.btnBorrowBook);
            this.panelBorrowingButtons.Dock = System.Windows.Forms.DockStyle.Bottom;
            this.panelBorrowingButtons.Location = new System.Drawing.Point(3, 467);
            this.panelBorrowingButtons.Name = "panelBorrowingButtons";
            this.panelBorrowingButtons.Size = new System.Drawing.Size(970, 50);
            this.panelBorrowingButtons.TabIndex = 0;
            // 
            // btnReturnBook
            // 
            this.btnReturnBook.Font = new System.Drawing.Font("Segoe UI", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnReturnBook.Location = new System.Drawing.Point(100, 10);
            this.btnReturnBook.Name = "btnReturnBook";
            this.btnReturnBook.Size = new System.Drawing.Size(80, 30);
            this.btnReturnBook.TabIndex = 1;
            this.btnReturnBook.Text = "Return";
            this.btnReturnBook.UseVisualStyleBackColor = true;
            // 
            // btnBorrowBook
            // 
            this.btnBorrowBook.Font = new System.Drawing.Font("Segoe UI", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnBorrowBook.Location = new System.Drawing.Point(0, 10);
            this.btnBorrowBook.Name = "btnBorrowBook";
            this.btnBorrowBook.Size = new System.Drawing.Size(80, 30);
            this.btnBorrowBook.TabIndex = 0;
            this.btnBorrowBook.Text = "Borrow";
            this.btnBorrowBook.UseVisualStyleBackColor = true;
            // 
            // panelBorrowingSearch
            // 
            this.panelBorrowingSearch.Controls.Add(this.btnClearBorrowingSearch);
            this.panelBorrowingSearch.Controls.Add(this.btnSearchBorrowing);
            this.panelBorrowingSearch.Controls.Add(this.txtSearchBorrowing);
            this.panelBorrowingSearch.Controls.Add(this.lblSearchBorrowing);
            this.panelBorrowingSearch.Dock = System.Windows.Forms.DockStyle.Top;
            this.panelBorrowingSearch.Location = new System.Drawing.Point(3, 3);
            this.panelBorrowingSearch.Name = "panelBorrowingSearch";
            this.panelBorrowingSearch.Size = new System.Drawing.Size(970, 50);
            this.panelBorrowingSearch.TabIndex = 2;
            // 
            // btnClearBorrowingSearch
            // 
            this.btnClearBorrowingSearch.Font = new System.Drawing.Font("Segoe UI", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnClearBorrowingSearch.Location = new System.Drawing.Point(530, 10);
            this.btnClearBorrowingSearch.Name = "btnClearBorrowingSearch";
            this.btnClearBorrowingSearch.Size = new System.Drawing.Size(80, 30);
            this.btnClearBorrowingSearch.TabIndex = 3;
            this.btnClearBorrowingSearch.Text = "Clear";
            this.btnClearBorrowingSearch.UseVisualStyleBackColor = true;
            // 
            // btnSearchBorrowing
            // 
            this.btnSearchBorrowing.Font = new System.Drawing.Font("Segoe UI", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnSearchBorrowing.Location = new System.Drawing.Point(440, 10);
            this.btnSearchBorrowing.Name = "btnSearchBorrowing";
            this.btnSearchBorrowing.Size = new System.Drawing.Size(80, 30);
            this.btnSearchBorrowing.TabIndex = 2;
            this.btnSearchBorrowing.Text = "Search";
            this.btnSearchBorrowing.UseVisualStyleBackColor = true;
            // 
            // txtSearchBorrowing
            // 
            this.txtSearchBorrowing.Font = new System.Drawing.Font("Segoe UI", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtSearchBorrowing.Location = new System.Drawing.Point(130, 13);
            this.txtSearchBorrowing.Name = "txtSearchBorrowing";
            this.txtSearchBorrowing.Size = new System.Drawing.Size(300, 33);
            this.txtSearchBorrowing.TabIndex = 1;
            // 
            // lblSearchBorrowing
            // 
            this.lblSearchBorrowing.AutoSize = true;
            this.lblSearchBorrowing.Font = new System.Drawing.Font("Segoe UI", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblSearchBorrowing.Location = new System.Drawing.Point(10, 16);
            this.lblSearchBorrowing.Name = "lblSearchBorrowing";
            this.lblSearchBorrowing.Size = new System.Drawing.Size(170, 28);
            this.lblSearchBorrowing.TabIndex = 0;
            this.lblSearchBorrowing.Text = "Search Borrowing:";
            // 
            // MainWindow
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(11F, 28F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(984, 561);
            this.Controls.Add(this.tabControlMain);
            this.Font = new System.Drawing.Font("Segoe UI", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.Name = "MainWindow";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "MyLibrary - Main Application";
            this.tabControlMain.ResumeLayout(false);
            this.tabPageBooks.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.dgvBooks)).EndInit();
            this.panelBookButtons.ResumeLayout(false);
            this.panelBookSearch.ResumeLayout(false);
            this.panelBookSearch.PerformLayout();
            this.tabPageBorrowers.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.dgvBorrowers)).EndInit();
            this.panelBorrowerButtons.ResumeLayout(false);
            this.panelBorrowerSearch.ResumeLayout(false);
            this.panelBorrowerSearch.PerformLayout();
            this.tabPageBorrowings.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.dgvBorrowings)).EndInit();
            this.panelBorrowingButtons.ResumeLayout(false);
            this.panelBorrowingSearch.ResumeLayout(false);
            this.panelBorrowingSearch.PerformLayout();
            this.ResumeLayout(false);

        }

        #endregion

        private System.Windows.Forms.TabControl tabControlMain;
        private System.Windows.Forms.TabPage tabPageBooks;
        private System.Windows.Forms.DataGridView dgvBooks;
        private System.Windows.Forms.Panel panelBookButtons;
        private System.Windows.Forms.Button btnDeleteBook;
        private System.Windows.Forms.Button btnEditBook;
        private System.Windows.Forms.Button btnAddBook;
        private System.Windows.Forms.TabPage tabPageBorrowers;
        private System.Windows.Forms.DataGridView dgvBorrowers;
        private System.Windows.Forms.Panel panelBorrowerButtons;
        private System.Windows.Forms.Button btnDeleteBorrower;
        private System.Windows.Forms.Button btnEditBorrower;
        private System.Windows.Forms.Button btnAddBorrower;
        private System.Windows.Forms.TabPage tabPageBorrowings;
        private System.Windows.Forms.DataGridView dgvBorrowings;
        private System.Windows.Forms.Panel panelBorrowingButtons;
        private System.Windows.Forms.Button btnReturnBook;
        private System.Windows.Forms.Button btnBorrowBook;
        private System.Windows.Forms.Panel panelBookSearch;
        private System.Windows.Forms.Label lblSearchBook;
        private System.Windows.Forms.TextBox txtSearchBook;
        private System.Windows.Forms.Button btnSearchBook;
        private System.Windows.Forms.Button btnClearBookSearch;
        private System.Windows.Forms.Panel panelBorrowerSearch;
        private System.Windows.Forms.Label lblSearchBorrower;
        private System.Windows.Forms.TextBox txtSearchBorrower;
        private System.Windows.Forms.Button btnSearchBorrower;
        private System.Windows.Forms.Button btnClearBorrowerSearch;
        private System.Windows.Forms.Panel panelBorrowingSearch;
        private System.Windows.Forms.Label lblSearchBorrowing;
        private System.Windows.Forms.TextBox txtSearchBorrowing;
        private System.Windows.Forms.Button btnSearchBorrowing;
        private System.Windows.Forms.Button btnClearBorrowingSearch;
    }
}